name: test and package pySubDisc

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Find SubDisc commit
      run: |
        echo "subdisc_commit=$(grep '^SubDisc' src/pysubdisc/VERSION | cut -d' ' -f 2)" >> $GITHUB_ENV

    - name: Checkout SubDisc
      uses: actions/checkout@v4
      with:
        repository: SubDisc/SubDisc
        ref: ${{ env.subdisc_commit }}
        path: ext/SubDisc
        # We need to fetch the full history because the commit count is used
        # to identify the SubDisc version.
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Build SubDisc with Maven
      run: mvn package
      working-directory: ./ext/SubDisc

    - name: Get SubDisc revision
      run: |
        echo "subdisc_revision=$(git -C ext/SubDisc rev-list HEAD --count)" >> $GITHUB_ENV

    - name: Copy jar
      run: |
        mkdir -p src/pysubdisc/jars
        cp ext/SubDisc/target/subdisc-gui.jar src/pysubdisc/jars/subdisc-gui-r${{ env.subdisc_revision }}.jar

    - name: Add jar version info
      run: |
        sed -i -e s/9999/${{ env.subdisc_revision }}/ src/pysubdisc/VERSION
        echo "pysubdisc_version=$(grep '^pySubDisc' src/pysubdisc/VERSION | cut -d' ' -f 2)" >> $GITHUB_ENV
        echo "Using SubDisc commit ${{ env.subdisc_commit }}, revision ${{ env.subdisc_revision }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest

    - name: Build package
      run: python -m build

    - name: Install
      run: pip install dist/pysubdisc-${{ env.pysubdisc_version }}-py3-none-any.whl

    - name: Test with pytest
      # The pytest faulthandler interferes with jpype
      run: pytest -p no:faulthandler

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Build conda package
      run: |
        conda install -y conda-build conda-verify
        conda build conda

    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: pysubdisc-wheel
        path: |
          dist/pysubdisc-${{ env.pysubdisc_version }}-py3-none-any.whl
          dist/pysubdisc-${{ env.pysubdisc_version }}.tar.gz
        retention-days: 2

    - name: Upload conda package
      uses: actions/upload-artifact@v3
      with:
        name: pysubdisc-conda
        path: /usr/share/miniconda/conda-bld/noarch/pysubdisc-${{ env.pysubdisc_version }}-py_*.tar.bz2
        retention-days: 2
